sudo: required  
dist: trusty 
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: php

php:
  - 7.1


install:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - php artisan serve & # Start server
  - sleep 5 # Give PhantomJS and Artisan time to start
            
script:
  - vendor/bin/phpunit
  - php artisan dusk

notifications:
  webhooks:
    urls:
      - https://forge.laravel.com/servers/96963/sites/278398/deploy/http?token=RNVYyt0rXXagSBNz2ZkqwM68i9G5t9qAUWVXR54g
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never   # default: never
    on_cancel: never # default: always
    on_error: never # default: always

  email: false