language: php

php:
  - 7.1


before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit

notifications:
  webhooks:
    urls:
      - https://forge.laravel.com/servers/96963/sites/278398/deploy/http?token=RNVYyt0rXXagSBNz2ZkqwM68i9G5t9qAUWVXR54g
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never   # default: never
    on_cancel: never # default: always
    on_error: never # default: always

  email: false